version: '3'
services:
    jogoteca_db:
        image: postgres:11.9-alpine
        environment:
            POSTGRES_PASSWORD: jogoteca-db-pw
            POSTGRES_USER: jogoteca-db-user
            POSTGRES_DB: jogoteca
        volumes:
            - jogoteca-db-data:/var/lib/postgresql/data
            - ${PWD}/postgresql/postgresql.conf:/etc/postgresql.conf
        ports:
            - "5555:5432"
        command: postgres
    jogoteca_app:
        build:
            context: ../Jogoteca.Web
            dockerfile: Dockerfile
        image: jogoteca/app
        environment:
            ASPNETCORE_URLS: http://+:80
        ports:
            - "5000:80"
        depends_on:
            - "jogoteca_db"
volumes:
    jogoteca-db-data: